name: chord_recognition
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - librosa
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow
  - pip:
      - liac-arff
